import Image from "next/image";
import { Card, CardContent } from "@/components/ui/card";

const examples = [
  {
    alt: "Social media app UI",
    src: "https://placehold.co/400x600.png",
    hint: "app ui",
  },
  {
    alt: "E-commerce app UI",
    src: "https://placehold.co/400x600.png",
    hint: "mobile interface",
  },
  {
    alt: "Fitness tracker app UI",
    src: "https://placehold.co/400x600.png",
    hint: "dashboard design",
  },
  {
    alt: "Music player app UI",
    src: "https://placehold.co/400x600.png",
    hint: "app design",
  },
];

export function Showcase() {
  return (
    <section className="py-20 md:py-28">
      <div className="container">
        <div className="mx-auto max-w-2xl text-center">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
            From Prompt to Production
          </h2>
          <p className="mt-4 text-muted-foreground">
            Explore a few examples of UIs generated by AI App Forge. Your next project could be just one conversation away.
          </p>
        </div>

        <div className="mt-12 grid grid-cols-2 gap-4 md:grid-cols-4 md:gap-8">
          {examples.map((example, index) => (
            <Card key={index} className="overflow-hidden border-border/50 bg-card/50 transition-transform duration-300 hover:-translate-y-2 hover:shadow-2xl hover:shadow-primary/20">
              <CardContent className="p-0">
                <Image
                  src={example.src}
                  alt={example.alt}
                  width={400}
                  height={600}
                  className="object-cover"
                  data-ai-hint={example.hint}
                />
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </section>
  );
}
